@orderId = ef43ddd3-be83-429f-8337-077d95a2383d
@baseUrl = http://localhost:8000/microservice-

### Create a Order
POST {{baseUrl}}orders/orders
Content-Type: application/json

{
    "value": 1000,
    "customerEmail": "lipe.dornelles@hotmail.com",
    "customerName": "Felipe Cliente 1"
}

### Fetching Orders
GET {{baseUrl}}orders/orders

### Pay a Order
PUT {{baseUrl}}payments/orders/{{orderId}}/pay

### Delivery a Order
PUT {{baseUrl}}orders/orders/{{orderId}}/delivery
